# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DZ', '0005_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trash',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='trash',
            name='user',
        ),
        migrations.DeleteModel(
            name='Trash',
        ),
    ]
